import Image from 'next/image';
import { BotIcon, ChevronDownIcon } from 'lucide-react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { cn } from '@/lib/utils';

const benefits = [
  {
    image: '/assets/setup-brand-banner1.webp',
    imageAlt: 'Product cards representing AI search visibility',
    background: 'bg-secondary',
    title: 'Track AI mentions',
    description:
      'See how often your brand appears when people ask AI platforms about your topic.',
  },
  {
    image: '/assets/setup-brand-banner2.webp',
    imageAlt: 'AI system connecting prompts across multiple devices',
    background: 'bg-primary/5',
    title: 'Discover trigger prompts',
    description:
      'Find the exact questions that cause ChatGPT and Gemini to mention your brand.',
  },
  {
    image: '/assets/setup-brand-banner3.webp',
    imageAlt: 'SEO expert researching artificial intelligence',
    background: 'bg-muted',
    title: 'Compare competitors',
    description:
      'Discover the brands mentioned beside you and the opportunities they currently own.',
  },
];

const questions = [
  {
    question: 'What is AI Search Visibility?',
    answer:
      'It measures how often and how prominently your brand appears in answers generated by AI search platforms.',
  },
  {
    question: 'Which AI platforms are checked?',
    answer:
      'RankSEO checks the same relevant customer prompts across ChatGPT and Gemini.',
  },
  {
    question: 'How are the prompts generated?',
    answer:
      'Your topic is used to create realistic informational, commercial, and comparison questions that potential customers may ask.',
  },
  {
    question: 'What does the visibility score represent?',
    answer:
      'The score combines brand mentions and whether AI answers cite your website.',
  },
  {
    question: 'How can I improve my AI visibility?',
    answer:
      'Use the report to find missing topics, competitor gaps, weak brand signals, and content that AI platforms are more likely to cite.',
  },
];

export function VisibilityLandingState() {
  return (
    <div className='flex flex-col gap-12 pb-10'>
      <section className='grid gap-5 md:grid-cols-3'>
        {benefits.map((benefit) => (
          <Card
            key={benefit.title}
            className='min-h-96 justify-between gap-3 rounded-xl border pb-0 shadow-none ring-0'
          >
            <CardHeader>
              <CardTitle className='text-2xl font-semibold tracking-tight normal-case'>
                {benefit.title}
              </CardTitle>
              <CardDescription>{benefit.description}</CardDescription>
            </CardHeader>
            <CardContent className='px-0'>
              <div
                className={cn(
                  'relative min-h-56 overflow-hidden rounded-b-xl',
                  benefit.background,
                )}
              >
                <Image
                  src={benefit.image}
                  alt={benefit.imageAlt}
                  fill
                  sizes='(min-width: 768px) 33vw, 100vw'
                  className='object-contain object-bottom px-5 pt-5'
                />
              </div>
            </CardContent>
          </Card>
        ))}
      </section>

      <section className='mx-auto flex w-full max-w-5xl flex-col gap-5'>
        <div className='flex items-center gap-3'>
          <BotIcon className='size-7 text-primary' aria-hidden='true' />
          <h2 className='text-3xl font-black tracking-tighter sm:text-4xl'>
            Questions answered
          </h2>
        </div>

        <div className='border-y'>
          {questions.map((item) => (
            <details
              key={item.question}
              className='group border-b last:border-b-0'
            >
              <summary className='flex cursor-pointer list-none items-center justify-between gap-4 py-5 font-semibold [&::-webkit-details-marker]:hidden'>
                {item.question}
                <ChevronDownIcon className='size-5 shrink-0 text-muted-foreground transition-transform group-open:rotate-180' />
              </summary>
              <p className='max-w-3xl pb-5 text-sm leading-relaxed text-muted-foreground'>
                {item.answer}
              </p>
            </details>
          ))}
        </div>
      </section>
    </div>
  );
}
